version: '3.1'

services:
  app:
    container_name: receiver-management-api
    build: .
    tty: true
    environment:
      DB_HOST: db
      DB_USER: app
      DB_NAME: receiver-management
      DB_PASSWORD: test
      DB_PORT: 5432
    ports:
      - "1323:1323"
    volumes:
      - .:/user/src/app
